default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  # encoding: unicode
  # collation: en_US.UTF-8
  database: contact_list_development
  pool: 5
  username: postgres
  password: postgres
test:
  adapter: postgresql
  # encoding: unicode
  # collation: en_US.UTF-8
  database: contact_list_test
  pool: 5
  username: postgres
  password: postgres